### ISSUE TITLE
ghacks_user.js.parrot proposed name change

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [atomGit/Firefox-user.js#1]
Hey atom - see https://github.com/ghacksuserjs/ghacks-user.js/issues/237

We want to rename `ghacks_user.js.parrot` to `_user.js.parrot` to make it the first pref in about:config. In order to this, we need to work together: is it possible for you to change your js to match, and of course update your article.

If you're OK with this, let me know :)  I haven't changed anything yet

**Comment by atomGit** [comment]
already changed it in my repo and i'll change it on my website in a few minutes

good idea BTW - thanks

also, i should have my search engine plugin article done very shortly - i'll let you know

**Comment by Thorin-Oakenpants** [comment]
Sweeet .. I'll do my commit now then

BTW - I have set up our wiki search pages - just two of them. 1. A basic list and 2. Example of how to sanitizing them. I'll be able to link your article at the beginning then :)

**Comment by atomGit** [comment]
> BTW - I have set up ...

yeah, i saw that

i just published the article - anything can be changed, so let me know what you think...

http://12bytes.org/articles/tech/firefox-search-engine-cautions-and-recommendations

you can use anything you want for your wiki

**Comment by Thorin-Oakenpants** [comment]
Awesome ... I need some zzzz's. Will check it out later. Will definitely link you as THE reference at the start. I have no idea when I will get around to it. Everything seems to fall to me and earthlng - and to just me for the wiki. I never intended it to get so big. And everyone comes up with ideas, and who f**king gets to do it `**sigh**` ... no idea when I will get around to it - every time I try, I balk at doing it and then something else comes up (or that's what I keep telling myself, lol)

I don't want to duplicate your work, but a simple list in the wiki with you as the main source will help drive you some traffic/recognition :)

**Comment by atomGit** [comment]
if i have permission to edit the wiki or somehow submit content, i might be able to help - i don't have all the time in the world either though - i dicked around for 6 months to get that article done :)

**Comment by Thorin-Oakenpants** [comment]
> i dicked around for 6 months to get that article done 

I'm seeing if I can stretch my case to 12 months .. lols

If I add you as a collaborator you should have access to the wiki editing - not sure if this auto adds you as a watcher and if you can change that - so maybe email notifications (and we can be quite noisy with our posts). At this stage I'm happy though - I want to make it super simple

One thing to mention (I haven't read the article yet, just an uber quick skim) - part of sanitizing is to stop the search engine results tracking you as well (_utm etc). It's outside the scope of the article, but worth mentioning - imagine people using a sanitized google engine and thinking they're "safe" or something.

**Comment by Thorin-Oakenpants** [comment]
Your article is linked top, front and center (and will stay there) in the two wiki pages [4.1](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Search-Engines) and [4.2](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2-Sanitizing) - at some stage I will enter a list and a basic sanitizing page

One thing I aim to highlight is search engines that do not require JS - eg DDG Lite

Also note, uBo filter to sanitize startpage.ixquick ( https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-uBlock-Origin#small_orange_diamond-filters )

**Comment by atomGit** [comment]
> You're already a collaborator with "Write access" go to the wiki and see if you can edit the search page

i thought you made be a collab earlier but i didn't know what the purpose was - and yes, apparently i can edit the wiki

> One thing I aim to highlight is search engines that do not require JS - eg DDG Lite

in that vein i added a 'Requires JS / Cookies' column to the [search engine table](http://12bytes.org/articles/tech/firefox-search-engine-cautions-and-recommendations#privacy-centric-search-engines)

interesting that DDG does not require JS to function IF i search from their page, however if i use the FF search plug-in, it does (and of course the /lite version never does - i added a link to it in the article)

i'll also add a note and link to the uBO filter for startpage/ixquick

**Comment by Thorin-Oakenpants** [comment]
Two heads are better than one  :beer: :beer:
